name: Nigthly packages build

on:
  push:
    branches: [ master ]

jobs:
  deb11:
    name: Debian 11 nightly package building
    runs-on: ubuntu-latest
    container: ghcr.io/yeti-switch/yeti-web/build-image:bullseye
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Build package
        run: make package
        env:
          PACKAGE_TYPE: nightly
      
      - name: Save deb package as artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb-package
          path: /__w/yeti-client/*.deb

      - name: Upload package to ${{github.ref}} repo
        env:
          PKG_API_BASE: ${{secrets.PKG_API_BASE}}
        run: ci/deploy.sh bullseye nightly main ../*.deb


